[[redirects]]
  from = "https://vguerrerobosch.netlify.com/*"
  to = "https://vguerrerobosch.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://vguerrerobosch.com/"
  to = "https://vguerrerobosch.com/"
  query = {lang = ":lang"}
  status = 301
  force = true
